title: Cloud-native Practices
email: 3zy4v335atyu+ghp@pm.me
description: >-
  Set of practices around cloud-native platforms, tools and apps.
baseurl: "/"
url: "https://joaquinfll.github.io"
github_username:  joaquinfll

remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed