title: Kim's Practices
email: 3zy4v335atyu+ghp@pm.me
description: >-
  Set of practices and recommendations aquired from experience and self-development.
baseurl: "/"
url: "https://joaquinfll.github.io"
github_username:  joaquinfll

theme: minima

plugins:
  - jekyll-feed